openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    API для роботи з контактною книгою. 
    Містить CRUD-операції для контактів та ендпоінти для авторизації користувачів,
    включаючи реєстрацію, логін, оновлення токенів, вихід та скидання пароля.
tags:
  - name: Auth
    description: Ендпоінти для авторизації та автентифікації користувачів.
  - name: Contacts
    description: Ендпоінти для управління контактами.
servers:
  - url: http://localhost:3000
    description: Локальний сервер
  - url: https://nodejs-hw-mongodb-kck1.onrender.com
    description: Продакшн-сервер (Render)

security:
  - bearerAuth: []

paths:
  /auth/register:
    $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    $ref: ../swagger/paths/auth/logout.yaml
  /auth/send-reset-email:
    $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    $ref: ../swagger/paths/auth/reset-pwd.yaml

  /contacts:
    $ref: ../swagger/paths/contacts/index.yaml

  /contacts/{contactId}:
    $ref: ../swagger/paths/contacts/{contactId}/index.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Contact:
      $ref: ../swagger/components/schemas/Contact.yaml
    Error:
      $ref: ../swagger/components/schemas/Error.yaml
